# Generated by Django 3.2.8 on 2021-10-10 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='image_category',
            field=models.ManyToManyField(to='photos.Category'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photos.location'),
            preserve_default=False,
        ),
    ]
