# Generated by Django 3.2.8 on 2021-10-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20211010_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='image_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_description',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.ImageField(upload_to=''),
        ),
    ]
