# Generated by Django 3.2.8 on 2021-10-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20211010_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_id',
            new_name='image',
        ),
    ]
