# Generated by Django 3.2.8 on 2021-10-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_rename_image_id_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
